### ISSUE TITLE
Kao CG Editor Todos

### ISSUE THREAD

**Issue by tzengyuxio** [tzengyuxio/kaodata#1]
### TODO:
7. [x] single select of figure
5. [x] update benchPlayer with game change  53dcd4a
1. [x] apply button
6. [x] refactor drag-and-drop and resize
2. [x] save and download button
4. [x] performance issue (change to hook kaodata itemID)
3. [ ] resize and apply of half-height image -> #3 
4. [ ] clipboard copy (add, remove) -> #2 
5. [ ] clipboard redraw when game changed with different palette, keep uint8array and img -> #2

**Comment by tzengyuxio** [comment]
已知 bug:
- 直接拖拉下方臉孔至拖拉上傳區，會跳錯誤 -> #4

**Comment by tzengyuxio** [comment]
New todos:
Must
- [x] change the "React App" title  1e771bd
- [x] instructions  42ae8f965cdb7929d4bda9dc0cd0eb7a1feb1807
- [x] add credits, link to koei-wiki  42ae8f965cdb7929d4bda9dc0cd0eb7a1feb1807
- [x] add buyme a coffee  42ae8f965cdb7929d4bda9dc0cd0eb7a1feb1807

Better Have
- [ ] add changelog page. -> #6
- [ ] display palette, modify and restore. -> #5
- [ ] find better parameter for RgbQuant -> #7
- [ ] skip RRBQuant if numColor less than 8 -> #8

**Comment by tzengyuxio** [comment]
未完成工作均已開 issue 紀錄。本 issue close.
